main:
    random_seed: 'nips2019'
    saved_dir: 'path-to-saved-directory'

dataset:
    name: 'VIPCUPSegDataset'
    kwargs:
        data_dir: 'path-to-processed-data'
        data_split_csv: 'path-to-data-split-csv-file'
        train_preprocessings:
            - name: 'Normalize'
            - name: 'PositiveCrop'
              kwargs:
                  positive_sampling_rate: 0.7
                  size: [192, 192, 48]
        valid_preprocessings:
            - name: 'Normalize'
            - name: 'PositiveCrop'
              kwargs:
                  positive_sampling_rate: 1.0
                  size: [192, 192, 48]
        augments:
            - name: 'RandomElasticDeformation'
            - name: 'RandomHorizontalFlip'
            - name: 'RandomVerticalFlip'
        transforms:
            - name: 'ToTensor'
            
dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 2
        valid_batch_size: 1
        shuffle: true
        num_workers: 4

net:
    name: 'DenseHighRes3DNet'
    kwargs:
        in_channels: 1
        out_channels: 2
        
losses:
    - name: 'BDLoss'
      weight: 1.0

metrics:
    - name: 'Dice'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001
        weight_decay: 0
        amsgrad: false

logger:
    name: 'VIPCUPSegLogger'
    kwargs:
        dummy_input: [16, 1, 128, 128]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 50
        early_stop: 0

trainer:
    name: 'VIPCUPSegTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 300
